--I don't particularly feel comfortable about this approach :\
--Updates colours to support UI elements for additional peers

	local num_player_slots = BigLobbyGlobals:num_player_slots()

	-- Override colours here, RGB values, divide by 255 to get a 0-1 value range that game wants
	local green = Vector3(194, 252, 151) / 255
	local blue = Vector3(120, 183, 204) / 255
	local red = Vector3(178, 104, 89) / 255
	local brown = Vector3(204, 161, 102) / 255
	local pink = Vector3(255, 182, 193) / 255
	local purple = Vector3(186, 90, 186) / 255
	local team_ai = Vector3(0.2, 0.8, 1)

	-- Fixed colours
	tweak_data.peer_vector_colors = {
		green,
		blue,
		red,
		brown,
		pink,
		purple
	}

	-- This doesn't appear to be referenced, not sure why it still exists in codebase
	tweak_data.peer_colors = {
		"mrgreen",
		"mrblue",
		"mrred",
		"mrpink",
		"mrbrown",
		"mrpurple"
	}

	-- Make sure we have enough colours to support the number of player slots, creates random colours
	if #tweak_data.peer_vector_colors < num_player_slots then
		-- We want random colours generated by the PRNG to be consistent across players, so use the same seed
		math.randomseed( 1337 )

		for i = #tweak_data.peer_vector_colors, num_player_slots do
			local red, blue, green -- rgb channels
			local random_colour
			red   = math.random(0, 255)
			green = math.random(0, 255)
			blue  = math.random(0, 255)
			random_colour = Vector3(red, green, blue) / 255

			table.insert(tweak_data.peer_vector_colors, random_colour)
			table.insert(tweak_data.peer_colors, tostring("team_colour_") .. i)
		end

		-- Make the seed randomish again, so other mods that rely on it don't get affected.
		math.randomseed( os.time() )
	end

	-- AI labels will use the last value so we add it at the end
	table.insert(tweak_data.peer_vector_colors, team_ai)
	table.insert(tweak_data.peer_colors, "mrai")

	-- Dynamically added now based on peer_vector_colors table
	tweak_data.chat_colors = {}
	for i = 1, #tweak_data.peer_vector_colors do
		tweak_data.chat_colors[i] = Color(tweak_data.peer_vector_colors[i]:unpack())
	end

	-- These hex colours don't have to match the equivalent rgb used above, but they should be similar,
	-- ai is not included as this is just for preplanning. The first ff is presumably for opacity, ff being 100% opaque

	-- Use the same colours created for chat for preplanning
	tweak_data.preplanning_peer_colors = {}
	for i = 1, #tweak_data.peer_vector_colors do
		tweak_data.preplanning_peer_colors[i] = Color(tweak_data.peer_vector_colors[i]:unpack())
	end

	-- Opted to use the chat colours generated above instead. So probably safe to delete this.
	-- tweak_data.preplanning_peer_colors = {
	-- 	Color("ff82991e"), --green
	-- 	Color("ff0055ff"), --blue
	-- 	Color("ffffb6c1"), --pink
	-- 	Color("ffffff00"), --yellow
	-- 	Color("ffff7800"), --red/orange, definitely orange
	-- 	Color("ffba5aba") --purple
	-- }


--Old version, technique only works with hoxhud enabled:
--[[
--Crashes if use global
--Updates colours to support UI elements for additional peers
orig_TweakData = orig_TweakData or {}
orig_TweakData.init = orig_TweakData.init or TweakData.init

function TweakData.init(self, ...)
	local num_player_slots = 6--BigLobbyGlobals:num_player_slots()

	orig_TweakData.init(self, ...)

	--override colours here, rgb values, /255 to get a 0-1 value range that game wants
	local brown = Vector3(204, 161, 102) / 255
	local green = Vector3(194, 252, 151) / 255
	local red = Vector3(178, 104, 89) / 255
	local blue = Vector3(120, 183, 204) / 255
	local pink = Vector3(255, 182, 193) / 255
	local purple = Vector3(186, 90, 186) / 255
	local team_ai = Vector3(0.2, 0.8, 1)

	self.peer_vector_colors = {
		green,
		blue,
		red,
		pink,
		brown,
		purple
	}

	--This doesn't appear to be referenced, not sure why it still exists in codebase
	self.peer_colors = {
		"mrgreen",
		"mrblue",
		"mrred",
		"mrpink",
		"mrbrown",
		"mrpurple"
	}

	-- Make sure we have enough colours to support the number of player slots, creates random colours
	if #self.peer_vector_colors < num_player_slots then
		for i = #self.peer_vector_colors, num_player_slots do
			--math.randomseed( os.time() ) --Will improve randomness of the PRNG
			local red, blue, green --rgb channels
			local random_colour
			red   = math.random(0, 255)
			green = math.random(0, 255)
			blue  = math.random(0, 255)
			random_colour = Vector3(red, green, blue) / 255

			table.insert(self.peer_vector_colors, random_colour)
			table.insert(self.peer_colors, tostring("team_colour_") .. i)
		end
	end

	--AI labels will use this
	table.insert(self.peer_vector_colors, team_ai)
	table.insert(self.peer_colors, "mrai")

	--Dynamically added now based on peer_vector_colors table
	self.chat_colors = {}
	for i = 1, #self.peer_vector_colors do
		self.chat_colors[i] = Color(self.peer_vector_colors[i]:unpack())
	end

	--These hex colours don't have to match the equivalent rgb used above, but they should be similar,
	--ai is not included as this is just for preplanning. The first ff is presumably for opacity, ff being 100% opaque
	self.preplanning_peer_colors = {
		Color("ff82991e"), --green
		Color("ff0055ff"), --blue
		Color("ffffb6c1"), --pink
		Color("ffffff00"), --yellow
		Color("ffff7800"), --red/orange, definitely orange
		Color("ffba5aba") --purple
	}
end
]]


-- moneytweakdata.lua - MoneyTweakData:init, fixes infinite money loss at the results/exp screen.
-- self.alive_humans_multiplier = self:_create_value_table(1, self.alive_players_max, BigLobbyGlobals:num_player_slots(), false, 1)
-- Hooking the function called instead, identifying the calling signature and correcting the parameter.
local orig__MoneyTweakData = {}
orig__MoneyTweakData._create_value_table = MoneyTweakData._create_value_table
function MoneyTweakData._create_value_table(min, max, table_size, round, curve)
	if (min == 1 and max == self.alive_players_max and table_size == 4 and round == false and curve == 1) then
		table_size = BigLobbyGlobals:num_player_slots()
	end

	orig__MoneyTweakData._create_value_table(self, min, max, table_size, round, curve)
end
